name: persuasion
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cuda-cccl_linux-64=12.6.77
  - cuda-command-line-tools=12.6.3
  - cuda-compiler=12.6.3
  - cuda-crt-dev_linux-64=12.6.85
  - cuda-crt-tools=12.6.85
  - cuda-cudart=12.6.77
  - cuda-cudart-dev=12.6.77
  - cuda-cudart-dev_linux-64=12.6.77
  - cuda-cudart-static=12.6.77
  - cuda-cudart-static_linux-64=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-cuobjdump=12.6.77
  - cuda-cupti=12.6.80
  - cuda-cupti-dev=12.6.80
  - cuda-cuxxfilt=12.6.77
  - cuda-driver-dev=12.6.77
  - cuda-driver-dev_linux-64=12.6.77
  - cuda-gdb=12.6.77
  - cuda-libraries=12.6.3
  - cuda-libraries-dev=12.6.3
  - cuda-nsight=12.6.77
  - cuda-nvcc=12.6.85
  - cuda-nvcc-dev_linux-64=12.6.85
  - cuda-nvcc-impl=12.6.85
  - cuda-nvcc-tools=12.6.85
  - cuda-nvcc_linux-64=12.6.85
  - cuda-nvdisasm=12.6.77
  - cuda-nvml-dev=12.6.77
  - cuda-nvprof=12.6.80
  - cuda-nvprune=12.6.77
  - cuda-nvrtc=12.6.85
  - cuda-nvrtc-dev=12.6.85
  - cuda-nvtx=12.6.77
  - cuda-nvvm-dev_linux-64=12.6.85
  - cuda-nvvm-impl=12.6.85
  - cuda-nvvm-tools=12.6.85
  - cuda-nvvp=12.6.80
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-sanitizer-api=12.6.77
  - cuda-toolkit=12.6.3
  - cuda-tools=12.6.3
  - cuda-version=12.6
  - cuda-visual-tools=12.6.3
  - dbus=1.13.18
  - expat=2.6.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.11.1.6
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.1
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libcublas=12.6.4.1
  - libcublas-dev=12.6.4.1
  - libcufft=11.3.0.4
  - libcufft-dev=11.3.0.4
  - libcufile=1.11.1.6
  - libcufile-dev=1.11.1.6
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.7.1.2
  - libcusolver-dev=11.7.1.2
  - libcusparse=12.5.4.2
  - libcusparse-dev=12.5.4.2
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.6.85
  - libnvjitlink-dev=12.6.85
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.39
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - ncurses=6.4
  - nsight-compute=2024.3.2.3
  - nspr=4.35
  - nss=3.89.1
  - openssl=3.0.15
  - pcre2=10.42
  - pip=24.2
  - python=3.12.7
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==1.1.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.42.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==24.2.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - compressed-tensors==0.8.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.1.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - fastapi==0.115.5
      - fastjsonschema==2.21.1
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fschat==0.2.36
      - fsspec==2024.9.0
      - gguf==0.10.0
      - git-filter-repo==2.47.0
      - gradio==5.7.1
      - gradio-client==1.5.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.26.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==9.1.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jiter==0.7.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lark==1.2.2
      - latex2mathml==3.77.0
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.9
      - markdown-it-py==3.0.0
      - markdown2==2.5.1
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.5.1
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nh3==0.2.19
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.55.0
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.12
      - outlines==0.0.46
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post4
      - peft==0.13.2
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==18.0.0
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - ray==2.39.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.21.0
      - ruff==0.8.1
      - safehttpx==0.1.6
      - safetensors==0.4.5
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - terminado==0.18.1
      - tiktoken==0.7.0
      - tinycss2==1.4.0
      - together==1.5.5
      - tokenizers==0.20.3
      - tomlkit==0.12.0
      - torch==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.1.0
      - typer==0.14.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - uvloop==0.21.0
      - vllm==0.6.4.post1
      - watchfiles==1.0.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - xformers==0.0.28.post3
      - xxhash==3.5.0
      - yarl==1.18.0
      - zipp==3.21.0
